version: "2"
services:
    client:
      build: ./client
      volumes:
        - ./client:/client
        - /client/node_modules
      ports:
        - 1337:3000
      depends_on:
        - api
    api:
      build: ./api
      restart: always
      ports:
        - 3001:3001
      volumes:
        - ./api:/api
        - /api/node_modules
      environment:
        - MONGO_URL=mongodb://mongodb:27017/20something
      entrypoint: ["./wait-for-it.sh","mongodb:27017","--timeout=0", "--", "npm", "start" ]
      depends_on:
        - mongodb
    mongodb:
      image: mongo
      restart: always
      volumes:
        - ./data-node:/data/db
      ports:
        - 24019:27017
      command: mongod --noauth --smallfiles

